RECOMMENDATION = {
    "strong_buy":5,
    "buy":4,
    "hold":3,
    "underperform_1":1,
    "underperform_2":2,
}

all_inputs = [
    [
        {
            # For 1st rule
            "days": 30,
            # For 2rd rule
            ### rule will be passed if recommendation of row is recommendation or rec_2
            "recommendation": [RECOMMENDATION['strong_buy'], RECOMMENDATION['buy']],
            # For 3rd rule
            ### rule will be passed if previous recommendation of row was recommendation_was or recommendation_was or rec_was_3
            "recommendation_was":[RECOMMENDATION['hold'], RECOMMENDATION['underperform_1'], RECOMMENDATION['underperform_2']],
            # For 4th rule
            ### rule will be passed if one of the peers is in the top 1/5/10
            "has_peers_filtering": True,
            "is_final_assessment_ascending": False,

            "event": "portfolio",
            "text_version": "text_1",
            "importance": 1,
        },
        {
            "days": 30,
            "recommendation": [RECOMMENDATION['strong_buy'], RECOMMENDATION['buy']],
            "recommendation_was": [RECOMMENDATION['strong_buy'], RECOMMENDATION['buy'], None],
            "has_peers_filtering": True,
            "is_final_assessment_ascending": False,
            "event": "portfolio",
            "text_version": "text_2",
            "importance": 1,
        },
        {
            "days": 30,
            "recommendation": [RECOMMENDATION['strong_buy'], RECOMMENDATION['buy']],
            "recommendation_was": [RECOMMENDATION['hold'], None, None],
            "has_peers_filtering": True,
            "is_final_assessment_ascending": False,
            "event": "portfolio",
            "text_version": "text_3",
            "importance": 1,
        },
        {
            "days": 30,
            "recommendation": [RECOMMENDATION['underperform_1'], RECOMMENDATION['underperform_2']],
            "recommendation_was": [RECOMMENDATION['underperform_1'], RECOMMENDATION['underperform_2'], None],
            "has_peers_filtering": True,
            "is_final_assessment_ascending": True,
            "event": "portfolio",
            "text_version": "text_4",
            "importance": 1,
        },
        {
            "days": 30,
            "recommendation": [RECOMMENDATION['underperform_1'], RECOMMENDATION['underperform_2']],
            "recommendation_was": [RECOMMENDATION['strong_buy'], RECOMMENDATION['buy'], None],
            "has_peers_filtering": True,
            "is_final_assessment_ascending": True,
            "event": "portfolio",
            "text_version": "text_5",
            "importance": 1,
        },
        {
            "days": 30,
            "recommendation": [RECOMMENDATION['underperform_1'], RECOMMENDATION['underperform_2']],
            "recommendation_was": [RECOMMENDATION['hold'], None, None],
            "has_peers_filtering": True,
            "is_final_assessment_ascending": True,
            "event": "portfolio",
            "text_version": "text_6",
            "importance": 1,
        },
        {
            "days": 30,
            "recommendation": [RECOMMENDATION['strong_buy'], RECOMMENDATION['buy']],
            "recommendation_was": [RECOMMENDATION['underperform_1'], RECOMMENDATION['underperform_2'], RECOMMENDATION['hold']],
            "has_peers_filtering": False,
            "is_final_assessment_ascending": True,
            "event": "portfolio",
            "text_version": "text_7",
            "importance": 1,
        },
        {
            "days": 30,
            "recommendation": [RECOMMENDATION['strong_buy'], RECOMMENDATION['buy']],
            "recommendation_was": [RECOMMENDATION['strong_buy'], RECOMMENDATION['buy'],None],
            "has_peers_filtering": False,
            "is_final_assessment_ascending": True,
            "event": "portfolio",
            "text_version": "text_8",
            "importance": 1,
        },
        {
            "days": 30,
            "recommendation": [RECOMMENDATION['underperform_1'], RECOMMENDATION['underperform_2']],
            "recommendation_was": [RECOMMENDATION['strong_buy'], RECOMMENDATION['buy'],None],
            "has_peers_filtering": False,
            "is_final_assessment_ascending": True,
            "event": "portfolio",
            "text_version": "text_9",
            "importance": 1,
        },
        {
            "days": 30,
            "recommendation": [RECOMMENDATION['underperform_1'], RECOMMENDATION['underperform_2']],
            "recommendation_was": [RECOMMENDATION['hold'], None, None],
            "has_peers_filtering": False,
            "is_final_assessment_ascending": True,
            "event": "portfolio",
            "text_version": "text_10",
            "importance": 1,
        },
        {
            "days": 30,
            "recommendation": [RECOMMENDATION['underperform_1'], RECOMMENDATION['underperform_2']],
            "recommendation_was": [RECOMMENDATION['underperform_1'], RECOMMENDATION['underperform_2'], None],
            "has_peers_filtering": False,
            "is_final_assessment_ascending": True,
            "event": "portfolio",
            "text_version": "text_11",
            "importance": 1,
        },
    ],

    [
        {
            "days": 30,
            "recommendation": [RECOMMENDATION['strong_buy'], RECOMMENDATION['buy']],
            "recommendation_was": [RECOMMENDATION['hold'], None, None],
            "part_of_top3": True,
            "event_type_top" : 3,
            "event": "top_3_industry",
            "text_version": "text_1",
            "importance": 2,
        },
        {
            "days": 30,
            "recommendation": [RECOMMENDATION['strong_buy'], RECOMMENDATION['buy']],
            "recommendation_was": [RECOMMENDATION['strong_buy'], RECOMMENDATION['buy'], None],
            "part_of_top3": True,
            "event_type_top" : 3,
            "event": "top_3_industry",
            "text_version": "text_2",
            "importance": 2,
        },
        {
            "days": 30,
            "recommendation": [RECOMMENDATION['strong_buy'], RECOMMENDATION['buy']],
            "recommendation_was": [RECOMMENDATION['underperform_1'], RECOMMENDATION['underperform_2'], None],
            "part_of_top3": True,
            "event_type_top" : 3,
            "event": "top_3_industry",
            "text_version": "text_3",
            "importance": 2,
        },
    ],
    [
        {
            "days": 30,
            "recommendation": [RECOMMENDATION['strong_buy'], RECOMMENDATION['buy']],
            "recommendation_was": [RECOMMENDATION['hold'], None, None],
            "part_of_top7": True,
            "event_type_top" : 7,
            "event": "top_7_sector",
            "text_version": "text_1",
            "importance": 3,
        },
        {
            "days": 30,
            "recommendation": [RECOMMENDATION['strong_buy'], RECOMMENDATION['buy']],
            "recommendation_was": [None,None,None],
            "part_of_top7": True,
            "event_type_top" : 7,
            "event": "top_7_sector",
            "text_version": "text_2",
            "importance": 3,
        },
        {
            "days": 30,
            "recommendation": [RECOMMENDATION['strong_buy'], RECOMMENDATION['buy']],
            "recommendation_was": [RECOMMENDATION['underperform_1'], RECOMMENDATION['underperform_2'], None],
            "part_of_top7": True,
            "event_type_top" : 7,
            "event": "top_7_sector",
            "text_version": "text_3",
            "importance": 3,
        },
    ],
    [
        {
            "days": 30,
            "recommendation": [RECOMMENDATION['strong_buy'], RECOMMENDATION['buy']],
            "recommendation_was": [RECOMMENDATION['underperform_1'], RECOMMENDATION['underperform_2'], None],
            "has_peers_filtering": False,
            "is_final_assessment_ascending": True,
            "rule_3": True,
            "event": "peers",
            "text_version": "text_1",
            "importance": 4,
        },
        {
            "days": 30,
            "recommendation": [RECOMMENDATION['strong_buy'], RECOMMENDATION['buy']],
            "recommendation_was": [RECOMMENDATION['underperform_1'], RECOMMENDATION['underperform_2'], None],
            "has_peers_filtering": True,
            "is_final_assessment_ascending": False,
            "event": "peers",
            "text_version": "text_2",
            "importance": 4,
        },
        {
            "days": 30,
            "recommendation": [RECOMMENDATION['strong_buy'], RECOMMENDATION['buy']],
            "recommendation_was": [RECOMMENDATION['strong_buy'], RECOMMENDATION['buy'], None],
            "has_peers_filtering": True,
            "is_final_assessment_ascending": False,
            "event": "peers",
            "text_version": "text_3",
            "importance": 4,
        },
        {
            "days": 30,
            "recommendation": [RECOMMENDATION['strong_buy'], RECOMMENDATION['buy']],
            "recommendation_was": [RECOMMENDATION['hold'], None, None],
            "has_peers_filtering": True,
            "is_final_assessment_ascending": False,
            "event": "peers",
            "text_version": "text_4",
            "importance": 4,
        },
        {
            "days": 30,
            "recommendation": [RECOMMENDATION['underperform_1'], RECOMMENDATION['underperform_2']],
            "recommendation_was": [RECOMMENDATION['underperform_1'], RECOMMENDATION['underperform_2'], None],
            "has_peers_filtering": True,
            "is_final_assessment_ascending": True,
            "event": "peers",
            "text_version": "text_5",
            "importance": 4,
        },
        {
            "days": 30,
            "recommendation": [RECOMMENDATION['underperform_1'], RECOMMENDATION['underperform_2']],
            "recommendation_was": [RECOMMENDATION['strong_buy'], RECOMMENDATION['buy'], None],
            "has_peers_filtering": True,
            "is_final_assessment_ascending": True,
            "event": "peers",
            "text_version": "text_6",
            "importance": 4,
        },
        {
            "days": 30,
            "recommendation": [RECOMMENDATION['underperform_1'], RECOMMENDATION['underperform_2']],
            "recommendation_was": [RECOMMENDATION['hold'], None, None],
            "has_peers_filtering": True,
            "is_final_assessment_ascending": True,
            "event": "peers",
            "text_version": "text_7",
            "importance": 4,
        },
        {
            "days": 30,
            "recommendation": [RECOMMENDATION['strong_buy'], RECOMMENDATION['buy']],
            "recommendation_was": [RECOMMENDATION['underperform_1'], RECOMMENDATION['underperform_2'], RECOMMENDATION['hold']],
            "has_peers_filtering": False,
            "is_final_assessment_ascending": True,
            "event": "peers",
            "text_version": "text_8",
            "importance": 4,
        },
        {
            "days": 30,
            "recommendation": [RECOMMENDATION['strong_buy'], RECOMMENDATION['buy']],
            "recommendation_was": [RECOMMENDATION['strong_buy'], RECOMMENDATION['buy'], None],
            "has_peers_filtering": False,
            "is_final_assessment_ascending": True,
            "event": "peers",
            "text_version": "text_9",
            "importance": 4,
        },
        {
            "days": 30,
            "recommendation": [RECOMMENDATION['underperform_1'], RECOMMENDATION['underperform_2']],
            "recommendation_was": [RECOMMENDATION['strong_buy'], RECOMMENDATION['buy'], None],
            "has_peers_filtering": False,
            "is_final_assessment_ascending": True,
            "event": "peers",
            "text_version": "text_10",
            "importance": 4,
        },
        {
            "days": 30,
            "recommendation": [RECOMMENDATION['underperform_1'], RECOMMENDATION['underperform_2']],
            "recommendation_was": [RECOMMENDATION['hold'], None, None],
            "has_peers_filtering": False,
            "is_final_assessment_ascending": True,
            "event": "peers",
            "text_version": "text_11",
            "importance": 4,
        },
        {
            "days": 30,
            "recommendation": [RECOMMENDATION['underperform_1'], RECOMMENDATION['underperform_2']],
            "recommendation_was": [RECOMMENDATION['underperform_1'], RECOMMENDATION['underperform_2'], None],
            "has_peers_filtering": False,
            "is_final_assessment_ascending": True,
            "event": "peers",
            "text_version": "text_12",
            "importance": 4,
        },
    ],
    [
        {
            "days": 30,
            "recommendation": [RECOMMENDATION['strong_buy'], RECOMMENDATION['buy']],
            "recommendation_was": [RECOMMENDATION['underperform_1'], RECOMMENDATION['underperform_2'], None],
            "has_peers_filtering": True,
            "is_final_assessment_ascending": False,
            "event": "large_market_cap",
            "text_version": "text_1",
            "importance": 5,
        },
        {
            "days": 30,
            "recommendation": [RECOMMENDATION['strong_buy'], RECOMMENDATION['buy']],
            "recommendation_was": [RECOMMENDATION['strong_buy'], RECOMMENDATION['buy'], None],
            "has_peers_filtering": True,
            "is_final_assessment_ascending": False,
            "event": "large_market_cap",
            "text_version": "text_2",
            "importance": 5,
        },
        {
            "days": 30,
            "recommendation": [RECOMMENDATION['strong_buy'], RECOMMENDATION['buy']],
            "recommendation_was": [RECOMMENDATION['hold'], None, None],
            "has_peers_filtering": True,
            "is_final_assessment_ascending": False,
            "event": "large_market_cap",
            "text_version": "text_3",
            "importance": 5,
        },
        {
            "days": 30,
            "recommendation": [RECOMMENDATION['underperform_1'], RECOMMENDATION['underperform_2']],
            "recommendation_was": [RECOMMENDATION['underperform_1'], RECOMMENDATION['underperform_2'], None],
            "has_peers_filtering": True,
            "is_final_assessment_ascending": True,
            "event": "large_market_cap",
            "text_version": "text_4",
            "importance": 5,
        },
        {
            "days": 30,
            "recommendation": [RECOMMENDATION['underperform_1'], RECOMMENDATION['underperform_2']],
            "recommendation_was": [RECOMMENDATION['strong_buy'], RECOMMENDATION['buy'], None],
            "has_peers_filtering": True,
            "is_final_assessment_ascending": True,
            "event": "large_market_cap",
            "text_version": "text_5",
            "importance": 5,
        },
        {
            "days": 30,
            "recommendation": [RECOMMENDATION['underperform_1'], RECOMMENDATION['underperform_2']],
            "recommendation_was": [RECOMMENDATION['hold'], None, None],
            "has_peers_filtering": True,
            "is_final_assessment_ascending": True,
            "event": "large_market_cap",
            "text_version": "text_6",
            "importance": 5,
        },
        {
            "days": 30,
            "recommendation": [RECOMMENDATION['strong_buy'], RECOMMENDATION['buy']],
            "recommendation_was": [RECOMMENDATION['underperform_1'], RECOMMENDATION['underperform_2'], RECOMMENDATION['hold']],
            "has_peers_filtering": False,
            "is_final_assessment_ascending": True,
            "event": "large_market_cap",
            "text_version": "text_7",
            "importance": 5,
        },
        {
            "days": 30,
            "recommendation": [RECOMMENDATION['strong_buy'], RECOMMENDATION['buy']],
            "recommendation_was": [RECOMMENDATION['strong_buy'], RECOMMENDATION['buy'], None],
            "has_peers_filtering": False,
            "is_final_assessment_ascending": True,
            "event": "large_market_cap",
            "text_version": "text_8",
            "importance": 5,
        },
        {
            "days": 30,
            "recommendation": [RECOMMENDATION['underperform_1'], RECOMMENDATION['underperform_2']],
            "recommendation_was": [RECOMMENDATION['strong_buy'], RECOMMENDATION['buy'], None],
            "has_peers_filtering": False,
            "is_final_assessment_ascending": True,
            "event": "large_market_cap",
            "text_version": "text_9",
            "importance": 5,
        },
        {
            "days": 30,
            "recommendation": [RECOMMENDATION['underperform_1'], RECOMMENDATION['underperform_2']],
            "recommendation_was": [RECOMMENDATION['hold'], None, None],
            "has_peers_filtering": False,
            "is_final_assessment_ascending": True,
            "event": "large_market_cap",
            "text_version": "text_10",
            "importance": 5,
        },
        {
            "days": 30,
            "recommendation": [RECOMMENDATION['underperform_1'], RECOMMENDATION['underperform_2']],
            "recommendation_was": [RECOMMENDATION['underperform_1'], RECOMMENDATION['underperform_2'], None],
            "has_peers_filtering": False,
            "is_final_assessment_ascending": True,
            "event": "large_market_cap",
            "text_version": "text_11",
            "importance": 5,
        },
    ],
]
