all_inputs = [
  [
  {
    'rec_1' : 4,
    'rec_2' : 5, 
    'rec_was_1' : 3,
    'rec_was_2' : 2,
    'rec_was_3' : 1,
    'final_assessment': True,
    'f_a_status' : False,
    'event':'portfolio',
    'text_version':'text_1', 
    'importance' : 1
},
{
    'rec_1' : 4,
    'rec_2' : 5, 
    'rec_was_1' : 4,
    'rec_was_2' : 5,
    'rec_was_3' : None,
    'final_assessment': True,
    'f_a_status' : False,
    'event':'portfolio',
    'text_version':'text_2', 
    'importance' : 1
},
{
    'rec_1' : 4,
    'rec_2' : 5, 
    'rec_was_1' : 3,
    'rec_was_2' : None,
    'rec_was_3' : None,
    'final_assessment': True,
    'f_a_status' : False,
    'event':'portfolio',
    'text_version':'text_3', 
    'importance' : 1
},
{
    'rec_1' : 1,
    'rec_2' : 2, 
    'rec_was_1' : 1,
    'rec_was_2' : 2,
    'rec_was_3' : None,
    'final_assessment': True,
    'f_a_status' : True,
    'event':'portfolio',
    'text_version':'text_4', 
    'importance' : 1
},
{
    'rec_1' : 1,
    'rec_2' : 2, 
    'rec_was_1' : 4,
    'rec_was_2' : 5,
    'rec_was_3' : None,
    'final_assessment': True,
    'f_a_status' : True,
    'event':'portfolio',
    'text_version':'text_5', 
    'importance' : 1
},
{
    'rec_1' : 1,
    'rec_2' : 2, 
    'rec_was_1' : 3,
    'rec_was_2' : None,
    'rec_was_3' : None,
    'final_assessment': True,
    'f_a_status' : True,
   'event':'portfolio',
   'text_version':'text_6', 
   'importance' : 1
},
{
    'rec_1' : 4,
    'rec_2' : 5, 
    'rec_was_1' : 1,
    'rec_was_2' : 2,
    'rec_was_3' : 3,
    'final_assessment': False,
    'f_a_status' : True,
    'event':'portfolio',
    'text_version':'text_7', 
    'importance' : 1
},
{
    'rec_1' : 4,
    'rec_2' : 5, 
    'rec_was_1' : 4,
    'rec_was_2' : 5,
    'rec_was_3' : None,
    'final_assessment': False,
    'f_a_status' : True,
    'event':'portfolio',
    'text_version':'text_8', 
    'importance' : 1
},
{
    'rec_1' : 1,
    'rec_2' : 2, 
    'rec_was_1' : 4,
    'rec_was_2' : 5,
    'rec_was_3' : None,
    'final_assessment': False,
    'f_a_status' : True,
    'event':'portfolio',
    'text_version':'text_9', 
    'importance' : 1
},
{
    'rec_1' : 1,
    'rec_2' : 2, 
    'rec_was_1' : 3,
    'rec_was_2' : None,
    'rec_was_3' : None,
    'final_assessment': False,
    'f_a_status' : True,
    'event':'portfolio',
    'text_version':'text_10', 
    'importance' : 1
},
{
    'rec_1' : 1,
    'rec_2' : 2, 
    'rec_was_1' : 1,
    'rec_was_2' : 2,
    'rec_was_3' : None,
    'final_assessment': False,
    'f_a_status' : True,
    'event':'portfolio',
    'text_version':'text_11', 
    'importance' : 1
},
],
  [
    {
    'rec_1' : 4,
    'rec_2' : 5, 
    'rec_was_1' : 3,
    'rec_was_2' : None,
    'rec_was_3' : None,  
    'part_of_top3': True,
    'event':'top_3_industry',
    'text_version':'text_1',
    'importance' : 2
  },
  {
    'rec_1' : 4,
    'rec_2' : 5, 
    'rec_was_1' : 4,
    'rec_was_2' : 5,
    'rec_was_3' : None,  
    'part_of_top3': True,
    'event':'top_3_industry',
    'text_version':'text_2', 
    'importance' : 2
  },
  {
    'rec_1' : 4,
    'rec_2' : 5, 
    'rec_was_1' : 1,
    'rec_was_2' : 2,
    'rec_was_3' : None,  
    'part_of_top3': True,
    'event':'top_3_industry',
    'text_version':'text_3', 
    'importance' : 2
  },
  ],
  [
    {
    'rec_1' : 4,
    'rec_2' : 5, 
    'rec_was_1' : 3,
    'rec_was_2' : None,
    'rec_was_3' : None,  
    'part_of_top7': True,
    'event':'top_7_sector',
    'text_version':'text_1', 
    'importance' : 3
  },
  {
    'rec_1' : 4,
    'rec_2' : 5, 
    'rec_was_1' : None,
    'rec_was_2' : None,
    'rec_was_3' : None,  
    'part_of_top7': True,
    'event':'top_7_sector',
    'text_version':'text_2', 
    'importance' : 3
  },
  {
    'rec_1' : 4,
    'rec_2' : 5, 
    'rec_was_1' : 1,
    'rec_was_2' : 2,
    'rec_was_3' : None,  
    'part_of_top7': True,
    'event':'top_7_sector',
    'text_version':'text_3', 
    'importance' : 3
  },
  ],
  [

    {
    'rec_1' : 4,
    'rec_2' : 5, 
    'rec_was_1' : 1,
    'rec_was_2' : 2,
    'rec_was_3' : None,
    'final_assessment': False,
    'f_a_status': True,
    'rule_3':True,
    'event':'peers',
    'text_version':'text_1', 
    'importance' : 4
  },{
    'rec_1' : 4,
    'rec_2' : 5, 
    'rec_was_1' : 1,
    'rec_was_2' : 2,
    'rec_was_3' : None,  
    'final_assessment': True,
    'f_a_status': False,
    'event':'peers',
    'text_version':'text_2', 
    'importance' : 4
  },{
    'rec_1' : 4,
    'rec_2' : 5, 
    'rec_was_1' : 4,
    'rec_was_2' : 5,
    'rec_was_3' : None,
    'final_assessment': True,
    'f_a_status': False,
    'event':'peers',
    'text_version':'text_3', 
    'importance' : 4
  },{
    'rec_1' : 4,
    'rec_2' : 5, 
    'rec_was_1' : 3,
    'rec_was_2' : None,
    'rec_was_3' : None,
    'final_assessment': True,
    'f_a_status': False,
    'event':'peers',
    'text_version':'text_4', 
    'importance' : 4
  },{
    'rec_1' : 1,
    'rec_2' : 2, 
    'rec_was_1' : 1,
    'rec_was_2' : 2,
    'rec_was_3' : None,
    'final_assessment': True, 
    'f_a_status': True,
    'event':'peers',
    'text_version':'text_5', 
    'importance' : 4
  },{
    'rec_1' : 1,
    'rec_2' : 2, 
    'rec_was_1' : 4,
    'rec_was_2' : 5,
    'rec_was_3' : None,
    'final_assessment': True,
    'f_a_status': True,
    'event':'peers',
    'text_version':'text_6', 
    'importance' : 4
  },{
    'rec_1' : 1,
    'rec_2' : 2, 
    'rec_was_1' : 3,
    'rec_was_2' : None,
    'rec_was_3' : None,
    'final_assessment': True,
    'f_a_status': True,
    'event':'peers',
    'text_version':'text_7', 
    'importance' : 4
  },{
    'rec_1' : 4,
    'rec_2' : 5, 
    'rec_was_1' : 1,
    'rec_was_2' : 2,
    'rec_was_3' : 3,
    'final_assessment': False,
    'f_a_status': True,
    'event':'peers',
    'text_version':'text_8', 
    'importance' : 4
  },{
    'rec_1' : 4,
    'rec_2' : 5, 
    'rec_was_1' : 4,
    'rec_was_2' : 5,
    'rec_was_3' : None,
    'final_assessment': False,
    'f_a_status': True,
    'event':'peers',
    'text_version':'text_9', 
    'importance' : 4
  },{
    'rec_1' : 1,
    'rec_2' : 2, 
    'rec_was_1' : 4,
    'rec_was_2' : 5,
    'rec_was_3' : None,
    'final_assessment': False,
    'f_a_status': True,
    'event':'peers',
    'text_version':'text_10', 
    'importance' : 4
  },{
    'rec_1' : 1,
    'rec_2' : 2, 
    'rec_was_1' : 3,
    'rec_was_2' : None,
    'rec_was_3' : None,
    'final_assessment': False,
    'f_a_status': True,
    'event':'peers',
    'text_version':'text_11', 
    'importance' : 4
  },{
    'rec_1' : 1,
    'rec_2' : 2, 
    'rec_was_1' : 1,
    'rec_was_2' : 2,
    'rec_was_3' : None,
    'final_assessment': False,
    'f_a_status': True,
    'event':'peers',
    'text_version':'text_12', 
    'importance' : 4
  }],
  [
{
  'rec_1' : 4,
  'rec_2' : 5, 
  'rec_was_1' : 1,
  'rec_was_2' : 2,
  'rec_was_3' : None,  
  'final_assessment': True,
  'f_a_status': False,
  'event':'large_market_cap',
  'text_version':'text_1', 
  'importance' : 5
},{
  'rec_1' : 4,
  'rec_2' : 5, 
  'rec_was_1' : 4,
  'rec_was_2' : 5,
  'rec_was_3' : None,
  'final_assessment': True,
  'f_a_status': False,
  'event':'large_market_cap',
  'text_version':'text_2', 
  'importance' : 5
},{
  'rec_1' : 4,
  'rec_2' : 5, 
  'rec_was_1' : 3,
  'rec_was_2' : None,
  'rec_was_3' : None,
  'final_assessment': True,
  'f_a_status': False,
  'event':'large_market_cap',
  'text_version':'text_3', 
  'importance' : 5
},{
  'rec_1' : 1,
  'rec_2' : 2, 
  'rec_was_1' : 1,
  'rec_was_2' : 2,
  'rec_was_3' : None,
  'final_assessment': True, 
  'f_a_status': True,
  'event':'large_market_cap',
  'text_version':'text_4', 
  'importance' : 5
},{
  'rec_1' : 1,
  'rec_2' : 2, 
  'rec_was_1' : 4,
  'rec_was_2' : 5,
  'rec_was_3' : None,
  'final_assessment': True,
  'f_a_status': True,
  'event':'large_market_cap',
  'text_version':'text_5', 
  'importance' : 5
},{
  'rec_1' : 1,
  'rec_2' : 2, 
  'rec_was_1' : 3,
  'rec_was_2' : None,
  'rec_was_3' : None,
  'final_assessment': True,
  'f_a_status': True,
  'event':'large_market_cap',
  'text_version':'text_6', 
  'importance' : 5
},{
  'rec_1' : 4,
  'rec_2' : 5, 
  'rec_was_1' : 1,
  'rec_was_2' : 2,
  'rec_was_3' : 3,
  'final_assessment': False,
  'f_a_status': True,
  'event':'large_market_cap',
  'text_version':'text_7', 
  'importance' : 5
},{
  'rec_1' : 4,
  'rec_2' : 5, 
  'rec_was_1' : 4,
  'rec_was_2' : 5,
  'rec_was_3' : None,
  'final_assessment': False,
  'f_a_status': True,
  'event':'large_market_cap',
  'text_version':'text_8', 
  'importance' : 5
},{
  'rec_1' : 1,
  'rec_2' : 2, 
  'rec_was_1' : 4,
  'rec_was_2' : 5,
  'rec_was_3' : None,
  'final_assessment': False,
  'f_a_status': True,
  'event':'large_market_cap',
  'text_version':'text_9', 
  'importance' : 5
},{
  'rec_1' : 1,
  'rec_2' : 2, 
  'rec_was_1' : 3,
  'rec_was_2' : None,
  'rec_was_3' : None,
  'final_assessment': False,
  'f_a_status': True,
  'event':'large_market_cap',
  'text_version':'text_10', 
  'importance' : 5
},{
  'rec_1' : 1,
  'rec_2' : 2, 
  'rec_was_1' : 1,
  'rec_was_2' : 2,
  'rec_was_3' : None,
  'final_assessment': False,
  'f_a_status': True,
  'event':'large_market_cap',
  'text_version':'text_11', 
  'importance' : 5
}]
]